### ISSUE TITLE
Ilias 7

### ISSUE THREAD

**Issue by slaudel** [ilifau/PCLimitedMediaPlayer#2]
Will this plugin be compatible with Ilias 7 and higher?

**Comment by fneumann** [comment]
A version for ILIAS 7 is yet planned, but you may test it by just increasing the version number. Please note that the plugin is not officially published in the plugin list of ILIAS. A new version for ILIAS 8 would require major refactorings - e.g. to get rid of the separate media item on the page that is automatically created. If you have interest in funding, please contact me.

**Comment by frauklee** [comment]
Hi,
do you have any news on this? Is it usable with ILIAS 7 by just increasing the version number? 
Are there already further developments for ILIAS 8 and is funding still needed?
